# Generated by Django 4.1.4 on 2022-12-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_classroom_table_alter_student_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProxy',
            fields=[
            ],
            options={
                'ordering': ['-id'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('management.student',),
        ),
    ]
