# Generated by Django 4.1.4 on 2022-12-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_studentproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('management.teacher',),
        ),
        migrations.AlterModelOptions(
            name='studentproxy',
            options={'ordering': ['id']},
        ),
    ]
