# Generated by Django 4.1.4 on 2022-12-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_teacherproxy_alter_studentproxy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teacher_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.teacher'),
            preserve_default=False,
        ),
    ]
