# Generated by Django 4.1.4 on 2022-12-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_classroom_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('grade', models.CharField(max_length=30)),
                ('evaluator', models.CharField(max_length=50)),
                ('exam_duration_min', models.IntegerField(default=0)),
                ('number_questions', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('grade', models.CharField(max_length=30)),
                ('evaluator', models.CharField(max_length=50)),
                ('theme_project', models.CharField(max_length=100)),
                ('numbers_groups', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='teacher_id',
            new_name='idTeacher',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='classroom_id',
            new_name='idClassroom',
        ),
        migrations.CreateModel(
            name='ProjectProxy',
            fields=[
            ],
            options={
                'ordering': ['theme_project'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('management.project',),
        ),
    ]
